### PR TITLE
Universal storage 2 solar fix

### PR DESCRIPTION
**Pull request by barak1001**
I wound up spending a few minutes last night figuring out why the Advanced Satellite's solar panels didn't work.  While I was at it I made a few changes to the gui to make it easier to navigate.
Tested and working in game.  I haven't figured out yet how to make the changes take effect on a part that's already been spawned in game, but it appears to work perfectly on parts in a new game.

### CODE REVIEW

**Review by linuxgurugamer — COMMENTED** [review]
The PR included a change to the .gitignore file, which conflicts with my process, I'm going to have to undo that change.  See below for the issue that this may have caused (5 deleted files)

It also looks like you reordered things in the AdvancedMicroSatWedge.cfg file, this  makes it harder to view the changes on Github since the diff first adds one section and then several dozen lines later, deletes the old version of the same section, from the line numbers they are in totally different locations

Why did you delete the science defs results for the USMapCam? and for the USTemperatureScan?  You may not use this in an atmosphere, but other people do.  Same goes for USbarometerScan, and the USCameraPicture?

Finally, you deleted five files which are used in my build process, I would have to recreate them from the previous commits (or start cherrypicking commit from the PR, which I don't like to do), looks like you tried to not do that with the change to .gitignore, but they are deleted.

Finally, you say this is to fix a problem with the solar panels on the advanced satellite, but the only changes I see is that you added the "isPersistant = false" to a number of the KSPFields in the USSolarSwitch.cs

**Comment by linuxgurugamer** [comment]
I appreciate the PR, am going over it now

Most of my  comments are in the review, please go over that

Can you be specific as to what the problem with the USAdvancedMicroSatWedge solar panels was, and specifically what you did to fix it?


I can't accept this in it's current state, you are changing existing functionality.  

I'm leaving the PR open, and if you can fix these problems, I'd be happy to accept it.

**Comment by barak1001** [comment]
I was fooling around with the Advanded Micro Sat wedge at the same time and honestly, I'm new to github.  The empty definitions for the variables in the file are what's causing the issue.  By defining them as empty they become read only.
I changed the a few things in the experiment definitions as well as the localizations so that the experiment names appear in game instead of autoloc....  I also made sure that the animations for the both experiments play automatically when they are deployed and the antenna deploys as well.

As far as deleting five files needed for rebuilding, I didn't realize if you approved the pull it would remove the files in question.  As I stated before I'm new to github.

I'm new to programming and mess around with it as a hobby.  I figured you can pick and choose whatever changes you'd like to keep, but as far as the solar panels go, this mod has been out for years and they've never worked because of the way the variables are defined for the animation.

**Comment by barak1001** [comment]
To be more precise, adding isPersistant = false didn't fix it, removing "= string.Empty" did.
Every one of those entries was read only and ignored the variable defined in the cfg file. Removing the definition of the variable solved the issue.

I changed the UScam and USTemperature to orbit only because they are only used in this mod by a satellite which only functions (correctly) when deployed in space.  I can't imagine a scenario where they'd use either experiment when in the atmosphere as provided by the mod.

The USmapCam is used by the cam wedge and isn't restricted to space.  The UScamerPicture is used only by the satellite.

In the atmosphere the normal temperature and barometer experiments are more than adequate.

Also should add that in all of the cfg files for parts that USsimpleScience experimentActionName needs to be defined in order for the name of the experiment to appear correctly in the GUI when you're looking at the RMB info for the part.

If you want I can resubmit the pull with minimal changes just to fix the solar issue, but the names not appearing correctly, and the game assigning you contracts where you need to take camera pictures in atmosphere from a satellite that can't fly in atmosphere is an issue.

**Pull request merged**
